export const BANK_SHORT_FORMS = {
  // Major Private Banks
  'HDFC Bank': 'hdfcbank',
  'ICICI Bank': 'icici',
  'Axis Bank': 'axl',
  'Yes Bank': 'ybl',
  'Kotak Mahindra Bank': 'kmbl',
  'IndusInd Bank': 'ibl',
  'Federal Bank': 'federal',
  'IDFC First Bank': 'idfcfirstbank',
  'RBL Bank': 'rbl',
  'South Indian Bank': 'sib',
  'Karur Vysya Bank': 'kvb',
  'Tamilnad Mercantile Bank': 'tmb',
  'Bandhan Bank': 'bandhan',
  'IDBI Bank': 'idbi',
  
  // Public Sector Banks
  'State Bank of India': 'sbi',
  'Punjab National Bank': 'pnb',
  'Bank of Baroda': 'bob',
  'Canara Bank': 'cnrb',
  'Union Bank of India': 'ubin',
  'Bank of India': 'boi',
  'Indian Bank': 'indianbank',
  'Central Bank of India': 'centralbank',
  'Indian Overseas Bank': 'iob',
  'UCO Bank': 'uco',
  'Bank of Maharashtra': 'bom',
  'Punjab and Sind Bank': 'psb',
  
  // Small Finance Banks
  'Equitas Small Finance Bank': 'equitas',
  'Ujjivan Small Finance Bank': 'ujjivan',
  'Jana Small Finance Bank': 'jana',
  'Fincare Small Finance Bank': 'fincare',
  'AU Small Finance Bank': 'aubank',
  'Capital Small Finance Bank': 'capitalbank',
  'ESAF Small Finance Bank': 'esaf',
  'North East Small Finance Bank': 'nesf',
  'Suryoday Small Finance Bank': 'suryoday',
  'Utkarsh Small Finance Bank': 'utkarsh',
  
  // Payments Banks
  'Paytm Payments Bank': 'paytm',
  'Airtel Payments Bank': 'airtel',
  'India Post Payments Bank': 'iippb',
  'Fino Payments Bank': 'fino',
  'Jio Payments Bank': 'jiomoney',
  'NSDL Payments Bank': 'nsdl',
  
  // Cooperative Banks
  'Saraswat Cooperative Bank': 'srcb',
  'Cosmos Cooperative Bank': 'cosmos',
  'TJSB Sahakari Bank': 'tjsb',
  'Mehsana Urban Cooperative Bank': 'msnu',
  'Rajkot Nagarik Sahakari Bank': 'rajkot',
  'Ahmednagar Merchants Cooperative Bank': 'amcb',
  'Bassein Catholic Cooperative Bank': 'bccb',
  'Dombivli Nagari Sahakari Bank': 'dnsb',
  'Jalgaon Janata Sahakari Bank': 'jjsb',
  'Kalyan Janata Sahakari Bank': 'kjsb',
  'Nutan Nagarik Sahakari Bank': 'nnsb',
  'Pune Merchants Cooperative Bank': 'pmcb',
  'Shamrao Vithal Cooperative Bank': 'svcb',
  'Thane Bharat Sahakari Bank': 'tbsb',
  'Zoroastrian Cooperative Bank': 'zcb',
  
  // Regional Rural Banks
  'Andhra Pradesh Grameena Vikas Bank': 'apgvb',
  'Andhra Pragathi Grameena Bank': 'apgb',
  'Arunachal Pradesh Rural Bank': 'aprb',
  'Assam Gramin Vikash Bank': 'agvb',
  'Bihar Gramin Bank': 'bgb',
  'Chhattisgarh Rajya Gramin Bank': 'crgb',
  'Dakshin Bihar Gramin Bank': 'dbgb',
  'Himachal Pradesh Gramin Bank': 'hpgb',
  'J&K Grameen Bank': 'jkgb',
  'Jharkhand Rajya Gramin Bank': 'jrgb',
  'Karnataka Gramin Bank': 'kgb',
  'Kerala Gramin Bank': 'kgb2',
  'Madhya Pradesh Gramin Bank': 'mpgb',
  'Maharashtra Gramin Bank': 'mgb',
  'Manipur Rural Bank': 'mrb',
  'Meghalaya Rural Bank': 'mrb2',
  'Mizoram Rural Bank': 'mrb3',
  'Nagaland Rural Bank': 'nrb',
  'Odisha Gramya Bank': 'ogb',
  'Puduvai Bharathiar Grama Bank': 'pbgb',
  'Punjab Gramin Bank': 'pgb',
  'Rajasthan Marudhara Gramin Bank': 'rmgb',
  'Sarva Haryana Gramin Bank': 'shgb',
  'Tamil Nadu Grama Bank': 'tngb',
  'Telangana Grameena Bank': 'tgb',
  'Tripura Gramin Bank': 'tgb2',
  'Uttar Bihar Gramin Bank': 'ubgb',
  'Uttarakhand Gramin Bank': 'ukgb',
  'Uttar Pradesh Gramin Bank': 'upgb',
  'West Bengal Gramin Bank': 'wbgb',
  
  // Foreign Banks
  'Citibank': 'citi',
  'Standard Chartered Bank': 'scb',
  'HSBC Bank': 'hsbc',
  'Deutsche Bank': 'deutsche',
  'Barclays Bank': 'barclays',
  'American Express Banking Corp': 'amex',
  'Bank of America': 'boa',
  'JPMorgan Chase Bank': 'chase',
  'Mizuho Bank': 'mizuho',
  'Sumitomo Mitsui Banking Corporation': 'smbc',
  'BNP Paribas': 'bnp',
  'Credit Suisse': 'creditsuisse',
  'UBS AG': 'ubs',
  'Abu Dhabi Commercial Bank': 'adcb',
  'Australia and New Zealand Banking Group': 'anz',
  'Bank of Bahrain and Kuwait': 'bbk',
  'Bank of Ceylon': 'boc',
  'Bank of Tokyo-Mitsubishi UFJ': 'btmu',
  'Commercial Bank of Qatar': 'cbq',
  'Crédit Agricole Corporate and Investment Bank': 'ca',
  'DBS Bank India': 'dbs',
  'Emirates NBD Bank': 'emirates',
  'First Abu Dhabi Bank': 'fab',
  'Mashreq Bank': 'mashreq',
  'National Australia Bank': 'nab',
  'Qatar National Bank': 'qnb',
  'Rabobank International': 'rabobank',
  'Royal Bank of Scotland': 'rbs',
  'Sberbank': 'sberbank',
  'Shinhan Bank': 'shinhan',
  'Société Générale': 'sg',
  'Sumitomo Mitsui Trust Bank': 'smtb',
  'The Bank of Nova Scotia': 'scotiabank',
  'The Hongkong and Shanghai Banking Corporation': 'hsbc2',
  'United Overseas Bank': 'uob',
  'Westpac Banking Corporation': 'westpac',
  'Woori Bank': 'woori'
}; 

export const getBankShortForm = (bankName) => {
  return BANK_SHORT_FORMS[bankName] || null;
};